export default[
    {
        id:'1',
        name:'张伟',
        num:'10001',
        gender:'男',
        age:'35',
        nationality:'汉族',
        marriage:'已婚',
        occupation:'工程师',
        patient:{
            name:'张伟'
        },
        treatmentSession:{
            count:1,
            data:"2024-2-5 15:30",
            duration:30,
            satisfaction:5.5,
            advice:'XXX'
        },
        phase:{
            treatmentCount:1,
            isEnded:false,
        }
    },
    {
        id:'2',
        name:'李娜',
        num:'10002',
        gender:'女',
        age:'31',
        nationality:'汉族',
        marriage:'已婚',
        occupation:'老师',
        patient:{
            name:'李娜'
        },
        treatmentSession:{
            count:1,
            data:"2024-2-5 15:30",
            duration:30,
            satisfaction:5.5,
            advice:'XXX'
        },
        phase:{
            treatmentCount:0,
            isEnded:false,
        }
    },
    {
        id:'3',
        name:'王强',
        num:'10003',
        gender:'男',
        age:'32',
        nationality:'汉族',
        marriage:'已婚',
        occupation:'建筑师',
        patient:{
            name:'王强'
        },
        treatmentSession:{
            count:1,
            data:"2024-2-5 15:30",
            duration:30,
            satisfaction:5.5,
            advice:'XXX'
        },
        phase:{
            treatmentCount:2,
            isEnded:false,
        }
    },
    {
        id:'4',
        name:'赵静',
        num:'10004',
        gender:'女',
        age:'28',
        nationality:'汉族',
        marriage:'已婚',
        occupation:'设计师',
        patient:{
            name:'赵静'
        },
        treatmentSession:{
            count:1,
            data:"2024-2-5 15:30",
            duration:30,
            satisfaction:5.5,
            advice:'XXX'
        },
        phase:{
            treatmentCount:3,
            isEnded:false,
        }
    },
    {
        id:'5',
        name:'刘洋',
        num:'10005',
        gender:'女',
        age:'21',
        nationality:'汉族',
        marriage:'未婚',
        occupation:'学生',
        patient:{
            name:'刘洋'
        },
        treatmentSession:{
            count:1,
            data:"2024-2-5 15:30",
            duration:30,
            satisfaction:5.5,
            advice:'XXX'
        },
        phase:{
            treatmentCount:2,
            isEnded:false,
        }
    },
    {
        id:'6',
        name:'孙丽',
        num:'10006',
        gender:'女',
        age:'34',
        nationality:'汉族',
        marriage:'已婚',
        occupation:'美食家',
        patient:{
            name:'孙丽'
        },
        treatmentSession:{
            count:1,
            data:"2024-2-5 15:30",
            duration:30,
            satisfaction:5.5,
            advice:'XXX'
        },
        phase:{
            treatmentCount:1,
            isEnded:false,
        }
    },
    {
        id:'7',
        name:'周伟',
        num:'10007',
        gender:'男',
        age:'32',
        nationality:'汉族',
        marriage:'已婚',
        occupation:'律师',
        patient:{
            name:'周伟'
        },
        treatmentSession:{
            count:1,
            data:"2024-2-5 15:30",
            duration:30,
            satisfaction:5.5,
            advice:'XXX'
        },
        phase:{
            treatmentCount:1,
            isEnded:false,
        }
    },
    {
        id:'8',
        name:'吴芳',
        num:'10008',
        gender:'女',
        age:'42',
        nationality:'汉族',
        marriage:'已婚',
        occupation:'工程师',
        patient:{
            name:'吴芳'
        },
        treatmentSession:{
            count:1,
            data:"2024-2-5 15:30",
            duration:30,
            satisfaction:5.5,
            advice:'XXX'
        },
        phase:{
            treatmentCount:0,
            isEnded:false,
        }
    },
    {
        id:'9',
        name:'郑军伟',
        num:'10009',
        gender:'男',
        age:'34',
        nationality:'汉族',
        marriage:'已婚',
        occupation:'工程师',
        patient:{
            name:'郑军伟'
        },
        treatmentSession:{
            count:1,
            data:"2024-2-5 15:30",
            duration:30,
            satisfaction:5.5,
            advice:'XXX'
        },
        phase:{
            treatmentCount:0,
            isEnded:false,
        }
    },
    {
        id:'10',
        name:'王丽',
        num:'10010',
        gender:'女',
        age:'37',
        nationality:'汉族',
        marriage:'已婚',
        occupation:'工程师',
        patient:{
            name:'王丽'
        },
        treatmentSession:{
            count:1,
            data:"2024-2-5 15:30",
            duration:30,
            satisfaction:5.5,
            advice:'XXX'
        },
        phase:{
            treatmentCount:0,
            isEnded:false,
        }
    },
    {
        id:'11',
        name:'陈伟',
        num:'10011',
        gender:'男',
        age:'31',
        nationality:'汉族',
        marriage:'已婚',
        occupation:'工程师',
        patient:{
            name:'陈伟'
        },
        treatmentSession:{
            count:1,
            data:"2024-2-5 15:30",
            duration:30,
            satisfaction:5.5,
            advice:'XXX'
        },
        phase:{
            treatmentCount:0,
            isEnded:false,
        }
    },
    {
        id:'12',
        name:'杨洋',
        num:'10012',
        gender:'女',
        age:'27',
        nationality:'汉族',
        marriage:'未婚',
        occupation:'工程师',
        patient:{
            name:'杨洋'
        },
        treatmentSession:{
            count:1,
            data:"2024-2-5 15:30",
            duration:30,
            satisfaction:5.5,
            advice:'XXX'
        },
        phase:{
            treatmentCount:0,
            isEnded:false,
        }
    },
    {
        id:'13',
        name:'黄静',
        num:'10013',
        gender:'女',
        age:'31',
        nationality:'汉族',
        marriage:'已婚',
        occupation:'工程师',
        patient:{
            name:'黄静'
        },
        treatmentSession:{
            count:1,
            data:"2024-2-5 15:30",
            duration:30,
            satisfaction:5.5,
            advice:'XXX'
        },
        phase:{
            treatmentCount:0,
            isEnded:false,
        }
    },
    {
        id:'14',
        name:'徐强',
        num:'10014',
        gender:'男',
        age:'25',
        nationality:'汉族',
        marriage:'未婚',
        occupation:'工程师',
        patient:{
            name:'张伟'
        },
        treatmentSession:{
            count:1,
            data:"2024-2-5 15:30",
            duration:30,
            satisfaction:5.5,
            advice:'XXX'
        },
        phase:{
            treatmentCount:0,
            isEnded:false,
        }
    
    },
    {
        id:'15',
        name:'张伟',
        num:'10015',
        gender:'男',
        age:'35',
        nationality:'汉族',
        marriage:'已婚',
        occupation:'工程师',
        patient:{
            name:'张伟'
        },
        treatmentSession:{
            count:1,
            data:"2024-2-5 15:30",
            duration:30,
            satisfaction:5.5,
            advice:'XXX'
        },
        phase:{
            treatmentCount:0,
            isEnded:false,
        }
    }
]